name: Trivy SCA

on:
  push:
      branches: [ "main" ]
  schedule:
    - cron: 0 12 * * 1
  # At 12:00 on Monday.
    
jobs:
    Trivy-Scan:
      permissions:
        contents: read # for actions/checkout to fetch code
        security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
        actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      name: Build
      runs-on: "ubuntu-20.04"
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
          
        - name: Running a scan with a sarif file as an output
          uses: aquasecurity/trivy-action@master
          with:
            scan-type: 'fs'
            format: 'template'
            template: '@/contrib/sarif.tpl'
            output: 'trivy-results.sarif'
            severity: 'LOW,MEDIUM,CRITICAL,HIGH'
            
        - name: Running a scan with a json file as an output
          uses: aquasecurity/trivy-action@master
          with:
            scan-type: 'fs'
            format: 'json'
            output: 'trivy-results.json'
            severity: 'LOW,MEDIUM,CRITICAL,HIGH'
            
        - name: Save the json vulnerability report to an artifact
          uses: actions/upload-artifact@v3
          with:
            name: trivy-results
            path: ./trivy-results.json
            
        - name: Upload Trivy scan results to GitHub Security tab
          uses: github/codeql-action/upload-sarif@v3
          with:
            sarif_file: 'trivy-results.sarif'
          
    Data_Analysis:
      name: Data Analysis
      needs: Trivy-Scan
      runs-on: ubuntu-latest
      steps:
        - name: Check out the code 
          uses: actions/checkout@v3

        - name: Download result for job Trivy-Scan
          uses: actions/download-artifact@v3
          with:
            name: trivy-results
            path: scan/
        
        - name: setup python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10' # install the python version needed

        - name: install python packages
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
    
        - name: Running the Python Script
          run: python abgabe.py scan/trivy-results.json "Trivy.txt" "ONOS"

        - name: Save plots to artifacts
          uses: actions/upload-artifact@v3
          with:
              name: plots
              path: |
                total_vulnerabilities_per_ric.png
                vulnerabilities_per_repo_ONOS.png
                vulnerabilities_per_repo_OSC.png
                severity_distribution_ONOS.png
                severity_distribution_OSC.png
                vulnerable_packages_per_ric.png
                vulnerable_packages_per_repo_ONOS.png
                vulnerable_packages_per_repo_OSC.png